/* Generated by Yosys 0.64+31 (git sha1 d51a5535c, g++ 11.5.0 -fPIC -O3) */

(* src = "RTL.v:46.1-68.10" *)
module safety_ctrl(clk, rst_n, win_error, data_in, action_reset, safe_out);
  (* src = "RTL.v:47.17-47.20" *)
  input clk;
  wire clk;
  (* src = "RTL.v:48.17-48.22" *)
  input rst_n;
  wire rst_n;
  (* src = "RTL.v:49.17-49.26" *)
  input win_error;
  wire win_error;
  (* src = "RTL.v:50.24-50.31" *)
  input [15:0] data_in;
  wire [15:0] data_in;
  (* src = "RTL.v:51.17-51.29" *)
  output action_reset;
  reg action_reset;
  (* src = "RTL.v:52.23-52.31" *)
  output [7:0] safe_out;
  reg [7:0] safe_out;
  (* src = "RTL.v:54.5-67.8" *)
  wire [7:0] _00_;
  assign _00_[6] = data_in[6] & ~(win_error);
  assign _00_[5] = data_in[5] & ~(win_error);
  assign _00_[4] = data_in[4] & ~(win_error);
  assign _00_[3] = data_in[3] & ~(win_error);
  assign _00_[2] = data_in[2] & ~(win_error);
  assign _00_[1] = data_in[1] & ~(win_error);
  assign _00_[0] = data_in[0] & ~(win_error);
  assign _00_[7] = data_in[7] & ~(win_error);
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) action_reset <= 1'h0;
    else action_reset <= win_error;
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) safe_out[0] <= 1'h0;
    else safe_out[0] <= _00_[0];
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) safe_out[1] <= 1'h0;
    else safe_out[1] <= _00_[1];
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) safe_out[2] <= 1'h0;
    else safe_out[2] <= _00_[2];
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) safe_out[3] <= 1'h0;
    else safe_out[3] <= _00_[3];
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) safe_out[4] <= 1'h0;
    else safe_out[4] <= _00_[4];
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) safe_out[5] <= 1'h0;
    else safe_out[5] <= _00_[5];
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) safe_out[6] <= 1'h0;
    else safe_out[6] <= _00_[6];
  (* src = "RTL.v:54.5-67.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) safe_out[7] <= 1'h0;
    else safe_out[7] <= _00_[7];
endmodule

(* src = "RTL.v:3.1-19.10" *)
module system_timebase(clk, rst_n, kick, system_reset_in, count);
  (* src = "RTL.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "RTL.v:5.17-5.22" *)
  input rst_n;
  wire rst_n;
  (* src = "RTL.v:6.17-6.21" *)
  input kick;
  wire kick;
  (* src = "RTL.v:7.17-7.32" *)
  input system_reset_in;
  wire system_reset_in;
  (* src = "RTL.v:8.24-8.29" *)
  output [15:0] count;
  reg [15:0] count;
  (* src = "RTL.v:11.5-18.8" *)
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  assign _001_ = count[0] & count[1];
  assign _002_ = count[2] & _001_;
  assign _003_ = count[3] & _002_;
  assign _004_ = count[4] & _003_;
  assign _005_ = count[5] & _004_;
  assign _006_ = count[6] & _005_;
  assign _007_ = count[7] & _006_;
  assign _008_ = count[8] & _007_;
  assign _009_ = count[9] & _008_;
  assign _010_ = count[10] & _009_;
  assign _011_ = count[11] & _010_;
  assign _012_ = count[12] & _011_;
  assign _013_ = count[13] & _012_;
  assign _014_ = ~(count[14] & _013_);
  assign _015_ = count[14] | _013_;
  assign _016_ = ~(kick | system_reset_in);
  assign _017_ = _015_ & _016_;
  assign _000_[14] = _014_ & _017_;
  assign _018_ = count[13] | _012_;
  assign _019_ = _016_ & _018_;
  assign _000_[13] = _019_ & ~(_013_);
  assign _020_ = count[12] | _011_;
  assign _021_ = _016_ & _020_;
  assign _000_[12] = _021_ & ~(_012_);
  assign _022_ = count[11] | _010_;
  assign _023_ = _016_ & _022_;
  assign _000_[11] = _023_ & ~(_011_);
  assign _024_ = count[10] | _009_;
  assign _025_ = _016_ & _024_;
  assign _000_[10] = _025_ & ~(_010_);
  assign _026_ = count[9] | _008_;
  assign _027_ = _016_ & _026_;
  assign _000_[9] = _027_ & ~(_009_);
  assign _028_ = count[8] | _007_;
  assign _029_ = _016_ & _028_;
  assign _000_[8] = _029_ & ~(_008_);
  assign _030_ = count[7] | _006_;
  assign _031_ = _016_ & _030_;
  assign _000_[7] = _031_ & ~(_007_);
  assign _032_ = count[6] | _005_;
  assign _033_ = _016_ & _032_;
  assign _000_[6] = _033_ & ~(_006_);
  assign _034_ = count[5] | _004_;
  assign _035_ = _016_ & _034_;
  assign _000_[5] = _035_ & ~(_005_);
  assign _036_ = count[4] | _003_;
  assign _037_ = _016_ & _036_;
  assign _000_[4] = _037_ & ~(_004_);
  assign _038_ = count[3] | _002_;
  assign _039_ = _016_ & _038_;
  assign _000_[3] = _039_ & ~(_003_);
  assign _040_ = count[2] | _001_;
  assign _041_ = _016_ & _040_;
  assign _000_[2] = _041_ & ~(_002_);
  assign _042_ = count[0] | count[1];
  assign _043_ = _016_ & _042_;
  assign _000_[1] = _043_ & ~(_001_);
  assign _000_[0] = _016_ & ~(count[0]);
  assign _044_ = ~(count[15] ^ _014_);
  assign _000_[15] = _016_ & _044_;
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[0] <= 1'h0;
    else count[0] <= _000_[0];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[1] <= 1'h0;
    else count[1] <= _000_[1];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[2] <= 1'h0;
    else count[2] <= _000_[2];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[3] <= 1'h0;
    else count[3] <= _000_[3];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[4] <= 1'h0;
    else count[4] <= _000_[4];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[5] <= 1'h0;
    else count[5] <= _000_[5];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[6] <= 1'h0;
    else count[6] <= _000_[6];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[7] <= 1'h0;
    else count[7] <= _000_[7];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[8] <= 1'h0;
    else count[8] <= _000_[8];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[9] <= 1'h0;
    else count[9] <= _000_[9];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[10] <= 1'h0;
    else count[10] <= _000_[10];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[11] <= 1'h0;
    else count[11] <= _000_[11];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[12] <= 1'h0;
    else count[12] <= _000_[12];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[13] <= 1'h0;
    else count[13] <= _000_[13];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[14] <= 1'h0;
    else count[14] <= _000_[14];
  (* src = "RTL.v:11.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[15] <= 1'h0;
    else count[15] <= _000_[15];
endmodule

(* top =  1  *)
(* src = "RTL.v:70.1-107.10" *)
module watchdog_system_top(clk, rst_n, kick, min_threshold, max_threshold, safe_state_out);
  (* src = "RTL.v:71.17-71.20" *)
  input clk;
  wire clk;
  (* src = "RTL.v:72.17-72.22" *)
  input rst_n;
  wire rst_n;
  (* src = "RTL.v:73.17-73.21" *)
  input kick;
  wire kick;
  (* src = "RTL.v:74.24-74.37" *)
  input [15:0] min_threshold;
  wire [15:0] min_threshold;
  (* src = "RTL.v:75.24-75.37" *)
  input [15:0] max_threshold;
  wire [15:0] max_threshold;
  (* src = "RTL.v:76.23-76.37" *)
  output [7:0] safe_state_out;
  wire [7:0] safe_state_out;
  (* src = "RTL.v:78.17-78.31" *)
  wire [15:0] internal_count;
  (* src = "RTL.v:79.10-79.24" *)
  wire internal_error;
  (* src = "RTL.v:80.10-80.24" *)
  wire internal_reset;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL.v:99.17-106.6" *)
  safety_ctrl u_ctrl (
    .action_reset(internal_reset),
    .clk(clk),
    .data_in(internal_count),
    .rst_n(rst_n),
    .safe_out(safe_state_out),
    .win_error(internal_error)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL.v:90.20-97.6" *)
  window_monitor u_mon (
    .clk(clk),
    .count(internal_count),
    .max_threshold(max_threshold),
    .min_threshold(min_threshold),
    .rst_n(rst_n),
    .win_error(internal_error)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL.v:82.21-88.6" *)
  system_timebase u_time (
    .clk(clk),
    .count(internal_count),
    .kick(kick),
    .rst_n(rst_n),
    .system_reset_in(internal_reset)
  );
endmodule

(* src = "RTL.v:21.1-44.10" *)
module window_monitor(clk, rst_n, count, min_threshold, max_threshold, win_error);
  (* src = "RTL.v:22.17-22.20" *)
  input clk;
  wire clk;
  (* src = "RTL.v:23.17-23.22" *)
  input rst_n;
  wire rst_n;
  (* src = "RTL.v:24.24-24.29" *)
  input [15:0] count;
  wire [15:0] count;
  (* src = "RTL.v:25.24-25.37" *)
  input [15:0] min_threshold;
  wire [15:0] min_threshold;
  (* src = "RTL.v:26.24-26.37" *)
  input [15:0] max_threshold;
  wire [15:0] max_threshold;
  (* src = "RTL.v:27.17-27.26" *)
  output win_error;
  reg win_error;
  (* src = "RTL.v:36.5-43.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  assign _047_ = _043_ & _046_;
  assign _048_ = _040_ & _047_;
  assign _049_ = _033_ & _048_;
  assign _050_ = count[6] & ~(max_threshold[6]);
  assign _051_ = ~(count[6] ^ max_threshold[6]);
  assign _052_ = count[7] | ~(max_threshold[7]);
  assign _053_ = count[5] | ~(max_threshold[5]);
  assign _054_ = max_threshold[7] | ~(count[7]);
  assign _055_ = _053_ & _054_;
  assign _056_ = _052_ & _055_;
  assign _057_ = _051_ & _056_;
  assign _058_ = max_threshold[4] | ~(count[4]);
  assign _059_ = max_threshold[5] | ~(count[5]);
  assign _060_ = _058_ & _059_;
  assign _061_ = count[4] | ~(max_threshold[4]);
  assign _062_ = _060_ & _061_;
  assign _063_ = _057_ & _062_;
  assign _064_ = max_threshold[3] | ~(count[3]);
  assign _065_ = max_threshold[2] | ~(count[2]);
  assign _066_ = ~(_064_ & _065_);
  assign _067_ = count[3] | ~(max_threshold[3]);
  assign _068_ = count[2] | ~(max_threshold[2]);
  assign _069_ = ~(_067_ & _068_);
  assign _070_ = ~(_066_ | _069_);
  assign _071_ = count[0] | ~(max_threshold[0]);
  assign _072_ = max_threshold[1] | ~(count[1]);
  assign _073_ = max_threshold[0] | ~(count[0]);
  assign _074_ = ~(max_threshold[1] ^ count[1]);
  assign _075_ = _071_ & _074_;
  assign _076_ = _070_ & _073_;
  assign _077_ = _075_ & _076_;
  assign _078_ = _063_ & _077_;
  assign _079_ = ~(_049_ & _078_);
  assign _080_ = _072_ & ~(_075_);
  assign _081_ = _080_ | ~(_070_);
  assign _082_ = ~(_066_ & _067_);
  assign _083_ = ~(_081_ & _082_);
  assign _084_ = ~(_063_ & _083_);
  assign _085_ = _060_ | ~(_057_);
  assign _086_ = ~(_050_ & _052_);
  assign _087_ = _054_ & _086_;
  assign _088_ = _085_ & _087_;
  assign _089_ = ~(_084_ & _088_);
  assign _090_ = ~(_049_ & _089_);
  assign _091_ = ~(_036_ & _037_);
  assign _092_ = ~(_040_ & _044_);
  assign _093_ = _043_ | _092_;
  assign _094_ = ~(_091_ & _093_);
  assign _095_ = ~(_033_ & _094_);
  assign _096_ = _030_ | ~(_027_);
  assign _097_ = ~(_020_ & _022_);
  assign _098_ = _024_ & _097_;
  assign _099_ = _096_ & _098_;
  assign _100_ = _095_ & _099_;
  assign _101_ = ~(_090_ & _100_);
  assign _102_ = ~(_079_ & _101_);
  assign _000_ = ~(_019_ & _102_);
  assign _103_ = count[6] | ~(min_threshold[6]);
  assign _104_ = min_threshold[5] | ~(count[5]);
  assign _105_ = count[0] | ~(min_threshold[0]);
  assign _106_ = count[1] | ~(min_threshold[1]);
  assign _107_ = ~(_105_ & _106_);
  assign _108_ = min_threshold[2] | ~(count[2]);
  assign _109_ = min_threshold[1] | ~(count[1]);
  assign _110_ = _108_ & _109_;
  assign _111_ = ~(_107_ & _110_);
  assign _112_ = count[3] | ~(min_threshold[3]);
  assign _113_ = count[2] | ~(min_threshold[2]);
  assign _114_ = _112_ & _113_;
  assign _115_ = ~(_111_ & _114_);
  assign _116_ = min_threshold[3] | ~(count[3]);
  assign _117_ = min_threshold[4] | ~(count[4]);
  assign _118_ = _116_ & _117_;
  assign _119_ = ~(_115_ & _118_);
  assign _120_ = count[5] | ~(min_threshold[5]);
  assign _121_ = count[4] | ~(min_threshold[4]);
  assign _122_ = _120_ & _121_;
  assign _123_ = ~(_119_ & _122_);
  assign _124_ = ~(_104_ & _123_);
  assign _125_ = ~(_103_ & _124_);
  assign _126_ = min_threshold[7] | ~(count[7]);
  assign _127_ = min_threshold[6] | ~(count[6]);
  assign _128_ = _126_ & _127_;
  assign _129_ = ~(_125_ & _128_);
  assign _130_ = min_threshold[11] | ~(count[11]);
  assign _131_ = count[9] | ~(min_threshold[9]);
  assign _132_ = count[11] | ~(min_threshold[11]);
  assign _133_ = count[10] & ~(min_threshold[10]);
  assign _134_ = _130_ & _132_;
  assign _135_ = ~(min_threshold[10] ^ count[10]);
  assign _136_ = _134_ & _135_;
  assign _137_ = _131_ & _136_;
  assign _138_ = min_threshold[9] | ~(count[9]);
  assign _139_ = min_threshold[8] | ~(count[8]);
  assign _140_ = _138_ & _139_;
  assign _141_ = count[7] | ~(min_threshold[7]);
  assign _142_ = count[8] | ~(min_threshold[8]);
  assign _143_ = _141_ & _142_;
  assign _144_ = _140_ & _143_;
  assign _145_ = _137_ & _144_;
  assign _146_ = ~(_129_ & _145_);
  assign _147_ = _140_ | ~(_137_);
  assign _148_ = ~(_132_ & _133_);
  assign _149_ = _130_ & _148_;
  assign _150_ = _147_ & _149_;
  assign _151_ = ~(_146_ & _150_);
  assign _152_ = min_threshold[15] | ~(count[15]);
  assign _001_ = count[15] | ~(min_threshold[15]);
  assign _002_ = count[14] & ~(min_threshold[14]);
  assign _003_ = count[13] | ~(min_threshold[13]);
  assign _004_ = _152_ & _003_;
  assign _005_ = ~(count[14] ^ min_threshold[14]);
  assign _006_ = _001_ & _005_;
  assign _007_ = _004_ & _006_;
  assign _008_ = min_threshold[13] | ~(count[13]);
  assign _009_ = min_threshold[12] | ~(count[12]);
  assign _010_ = ~(_008_ & _009_);
  assign _011_ = count[12] | ~(min_threshold[12]);
  assign _012_ = ~(_007_ & _011_);
  assign _013_ = ~(_010_ | _012_);
  assign _014_ = ~(_151_ & _013_);
  assign _015_ = ~(_007_ & _010_);
  assign _016_ = ~(_001_ & _002_);
  assign _017_ = _152_ & _016_;
  assign _018_ = _015_ & _017_;
  assign _019_ = ~(_014_ & _018_);
  assign _020_ = count[14] & ~(max_threshold[14]);
  assign _021_ = ~(count[14] ^ max_threshold[14]);
  assign _022_ = count[15] | ~(max_threshold[15]);
  assign _023_ = count[13] | ~(max_threshold[13]);
  assign _024_ = max_threshold[15] | ~(count[15]);
  assign _025_ = _023_ & _024_;
  assign _026_ = _022_ & _025_;
  assign _027_ = _021_ & _026_;
  assign _028_ = max_threshold[12] | ~(count[12]);
  assign _029_ = max_threshold[13] | ~(count[13]);
  assign _030_ = _028_ & _029_;
  assign _031_ = count[12] | ~(max_threshold[12]);
  assign _032_ = _030_ & _031_;
  assign _033_ = _027_ & _032_;
  assign _034_ = max_threshold[11] | ~(count[11]);
  assign _035_ = max_threshold[10] | ~(count[10]);
  assign _036_ = ~(_034_ & _035_);
  assign _037_ = count[11] | ~(max_threshold[11]);
  assign _038_ = count[10] | ~(max_threshold[10]);
  assign _039_ = ~(_037_ & _038_);
  assign _040_ = ~(_036_ | _039_);
  assign _041_ = max_threshold[9] | ~(count[9]);
  assign _042_ = max_threshold[8] | ~(count[8]);
  assign _043_ = _041_ & _042_;
  assign _044_ = count[9] | ~(max_threshold[9]);
  assign _045_ = count[8] | ~(max_threshold[8]);
  assign _046_ = _044_ & _045_;
  (* src = "RTL.v:36.5-43.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) win_error <= 1'h0;
    else win_error <= _000_;
endmodule
